WIP Benchmarks: about the data Page
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #2431
Opened 2020-08-18 15:45 UTC by g-m-taylor

WIP

#### Tests
Does this PR include tests for the changes introduced?
- [ ] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2020-08-19 08:17 UTC, aaron-russell requested changes

2020-08-19 08:17 UTC, aaron-russell commented on src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.html
> +      </ul>
You can just add those classes to the UL. The LI's will inherit it

2020-08-19 08:17 UTC, aaron-russell commented on src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts
> +            console.log(data);
Console log

2020-08-19 08:17 UTC, aaron-russell commented on src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts
> +  }
I think you can juse pipe it to a global formatter?

2020-08-19 11:43 UTC, chadtomkiss-madetech commented on src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts
> +  }
@aaron-russell yeah, you can do:

```
{{ meta.staff | number }}
```

in the template

2020-08-20 08:23 UTC, aaron-russell requested changes

2020-08-20 08:23 UTC, aaron-russell commented on src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts
> +  }
You're not doing anything onDestroy, is it needed?

2020-08-20 08:23 UTC, aaron-russell commented on src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts
> +  }
Or are you meaning to unsubscribe on destroy?

2020-08-20 09:32 UTC, g-m-taylor commented on src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts
> +  }
I will need to for the unsubscribe, but also TS complains when it doesnt exist

2020-08-24 08:01 UTC, merged