Turnover ranking
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #2686
Opened 2020-11-18 17:07 UTC by madeviv

#### Tests
Does this PR include tests for the changes introduced?
- [X] Yes
- [ ] No, I found it difficult to test
- [] No, they are not required for this change

2020-11-18 17:21 UTC, aaron-russell requested changes

2020-11-18 17:21 UTC, aaron-russell commented on server/models/benchmarksTurnover.js
> +  const BenchmarksPay = sequelize.define(
This should be `BenchmarksTurnover`

2020-11-18 17:21 UTC, aaron-russell commented on src/app/shared/components/benchmark-metric/barchart/barchart-options-builder.ts
>        const bold = this.isFirst ? 'govuk-!-font-weight-bold' : 'govuk-!-font-weight-regular';
You can get rid of this line

2020-11-18 17:26 UTC, madeviv commented on server/models/benchmarksTurnover.js
> +  const BenchmarksPay = sequelize.define(
Good catch

2020-11-19 10:16 UTC, aaron-russell approved these changes

2020-11-19 10:54 UTC, aaron-russell approved these changes

2020-11-19 11:01 UTC, merged