WIP: Feat/delete report
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #2709
Opened 2020-11-23 12:13 UTC by g-m-taylor

#### Tests
Does this PR include tests for the changes introduced?
- [x] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2020-11-23 13:54 UTC, aaron-russell reviewed
I think you may need to rebase and refactor before you merge, some of the CSSR stuff has changed I think

2020-11-23 13:54 UTC, aaron-russell commented on server/models/establishment.js
> +
Why is this in the deletions report PR?

2020-11-23 14:01 UTC, aaron-russell requested changes

2020-11-23 14:01 UTC, aaron-russell commented on src/app/features/reports/pages/reports/reports.component.html
> +            href="/download/{{ now | date: 'yyyy-MM-dd' }}-delete-report.csv"
needs to be xlsx?

2020-11-23 14:48 UTC, g-m-taylor commented on server/routes/reports/deleteReport/report.js
> +  };
I was wondering that but they are fairly specific to this one excel sheet so wasnt sure its worth it?

2020-11-23 14:57 UTC, aaron-russell commented on server/routes/reports/deleteReport/report.js
> +  };
Where you're making the headers blue, think that could definitely be a util, Where you're adding the date, maybe not. I guess it may be best having a util to make the background of a cell blue, then passing the cells you want?

2020-11-23 15:19 UTC, g-m-taylor commented on server/models/establishment.js
> +
I think because I ran auto formatting ?

2020-11-23 16:16 UTC, aaron-russell commented on server/routes/reports/deleteReport/report.js
> +  };
Can some of these functions be moved out of the route? And just be in the root of the file

2020-11-24 09:35 UTC, madeviv commented on server/models/establishment.js
> +
This seems quite out of date. Think you need to merge from test

2020-11-24 11:45 UTC, madeviv commented on server/models/establishment.js
> +  Establishment.getBenchmarkData = async function (establishmentId) {
Pretty sure this function should be in `models/benchmarks.js`

2020-11-24 12:56 UTC, g-m-taylor commented on server/models/establishment.js
> +
yeah just merged the latest changes

2020-11-24 12:57 UTC, g-m-taylor commented on server/routes/reports/deleteReport/report.js
> +  };
yeah the reusable ones have been moved

2020-11-25 13:51 UTC, aaron-russell approved these changes

2020-11-25 13:54 UTC, merged