Feat: Benchmark PDFs for Sickness, Quals, Pay & Turnover
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #2736
Opened 2020-12-03 16:04 UTC by chadtomkiss-madetech

**Work done**

- Updated `BuildBenchmarksPdf` to work with individual benchmarks
- Refactored creation of PDF into smaller funcs (for adding header/footer/about the data etc)
- Added `canvg` to convert SVGS into Canvas elements so that the charts can be rendered in the PDF
- Remove `html2canvas` as a top level dependency (is pulled in via `jspdf`)

#### Tests
Does this PR include tests for the changes introduced?
- [ ] Yes
- [ ] No, I found it difficult to test
- [x] No, they are not required for this change

2020-12-03 16:07 UTC, chadtomkiss-madetech commented on src/app/core/services/pdf.service.ts
> +
Not sure how I feel about this - it's used to calculate where the footer at the bottom should go on each page

2020-12-03 16:08 UTC, chadtomkiss-madetech commented on src/app/core/services/pdf.service.ts
> +export enum ReportType {
Should the terminology be `Report`? We already have Training Reports etc and this is for the Benchmarks PDF

2020-12-03 16:09 UTC, chadtomkiss-madetech commented on src/app/core/services/pdf.service.ts
> +  public ypx = (this.y * this.ptToPx) / this.scale;
I moved these to be class properties in order to reference them in other functions but there might be a better way?

2020-12-03 16:23 UTC, madeviv commented on src/app/core/services/pdf.service.ts
> +
Would it not be easier to get ReportType and ReportInterface and just have a separate BuildMetricsPdf public function on PdfService

2020-12-03 16:26 UTC, madeviv commented on src/app/core/services/pdf.service.ts
> +export enum ReportType {
Would it not be easier to get rid of ReportType and ReportInterface and just have a separate BuildMetricsPdf public function on PdfService

2020-12-03 16:28 UTC, madeviv commented on src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts
> +      );
I would probably do away with having a catch all BuildBenchmarksPdf function and create a separate function for metrics then you don't need to increase the number of arguments

2020-12-07 10:13 UTC, aaron-russell requested changes

2020-12-07 10:13 UTC, aaron-russell commented on src/assets/scss/modules/_utils.scss
> +
Missed a trick not calling it .ninja! Should we be using `!important`?

2020-12-07 10:36 UTC, chadtomkiss-madetech commented on src/assets/scss/modules/_utils.scss
> +
Funny enough there is already:

```
.hidden {
  display: none !important;
}
```

in `benchmarks-tab.component.scss`

I don't think the `!important` is an issue - I think utility classes are a good option for using it? I also don't think we would ever want to override the display of an element that has a `hidden` class on it?

Suggestion: move `.hidden` to `_utils.scss` and replace `util__hidden` classes with `hidden`?

2020-12-07 13:08 UTC, aaron-russell commented on src/assets/scss/modules/_utils.scss
> +
Sounds good

2020-12-07 14:21 UTC, chadtomkiss-madetech commented on src/assets/scss/modules/_utils.scss
> +
@aaron-russell it was an old class that wasn't used - we don't have an About the data link on the individual tile pages so don't need to hide the component

2020-12-07 14:34 UTC, aaron-russell approved these changes

2020-12-07 15:02 UTC, merged