about-bulk-upload
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #2782
Opened 2020-12-14 15:22 UTC by g-m-taylor

Add a page about the bulk upload 

#### Tests
Does this PR include tests for the changes introduced?
- [ ] Yes
- [ ] No, I found it difficult to test
- [x] No, they are not required for this change

2020-12-14 15:37 UTC, chadtomkiss-madetech requested changes

2020-12-14 15:37 UTC, chadtomkiss-madetech commented on src/app/core/breadcrumb/journey.bulk-upload.ts
> +          children: [],
Don't think we need `children` here

2020-12-14 15:37 UTC, chadtomkiss-madetech commented on src/app/features/bulk-upload/v2/about-bulk-upload/about-bulk-upload.component.ts
> +  providers: [],
Do we need `providers` if it's an empty array?

2020-12-14 15:37 UTC, chadtomkiss-madetech commented on src/app/features/bulk-upload/v2/about-bulk-upload/about-bulk-upload.component.html
> +    <button type="submit" class="govuk-button govuk-!-margin-top-6" (click)="return()">Return to bulk upload</button>
This button isn't submitting a form and is actually a link.

The markup to make links look like buttons is:

```
<a role="button" draggable="false" class="govuk-button" [routerLink]="['/login']">
    Go to sign in
</a>
```

2020-12-14 15:42 UTC, chadtomkiss-madetech commented on src/app/features/bulk-upload/v2/about-bulk-upload/about-bulk-upload.component.ts
> +import { Component, OnDestroy, OnInit } from '@angular/core';
Unused `OnDestroy`

2020-12-14 16:30 UTC, madeviv requested changes
I've changed the file structure for new BU to be under `/bulk-upload-v2` rather than `/bulk-upload/v2` to make it easier to navigate so you may want to wait for my ticket to be merged first as we might conflict

2020-12-16 12:03 UTC, madeviv approved these changes

2020-12-17 09:24 UTC, chadtomkiss-madetech approved these changes

2020-12-17 09:26 UTC, merged