Feat/accessibility update
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #2844
Opened 2021-01-06 14:59 UTC by joannafawl

#### Tests
Does this PR include tests for the changes introduced?
- [ ] Yes
- [ ] No, I found it difficult to test
- [x] No, they are not required for this change

2021-01-06 15:39 UTC, aaron-russell requested changes

2021-01-06 15:39 UTC, aaron-russell commented on src/app/features/public/accessibility-statement/accessibility-statement.component.html
> +      We’re always looking to improve the accessibility of this website. If you find any problems not listed on this
I think that's a weird encoded apostrophe?

2021-01-06 16:03 UTC, joannafawl commented on src/app/features/public/accessibility-statement/accessibility-statement.component.html
> +      We’re always looking to improve the accessibility of this website. If you find any problems not listed on this
Yeah I changed the apostrophes from &apos; to how they are in the html file I was updating from, do you want me to change them back?

2021-01-07 09:59 UTC, aaron-russell commented on src/app/features/public/accessibility-statement/accessibility-statement.component.html
> +      We’re always looking to improve the accessibility of this website. If you find any problems not listed on this
It's because it's kind od sideways, if that makes sense... I don't know the proper name for it! The difference between `’` and `'`. Sometimes fonts struggle with the sideways apostrophes .

2021-01-07 11:54 UTC, joannafawl commented on src/app/features/public/accessibility-statement/accessibility-statement.component.html
> +      We’re always looking to improve the accessibility of this website. If you find any problems not listed on this
Oh I see what you mean, I'll change them now

2021-01-08 10:36 UTC, aaron-russell approved these changes

2021-01-08 11:55 UTC, merged