WIP: Bu/missing ref: Workflow for missing references
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #2992
Opened 2021-02-17 12:11 UTC by g-m-taylor

#### Tests
Does this PR include tests for the changes introduced?
- [x] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2021-02-22 13:33 UTC, aaron-russell requested changes

2021-02-22 13:33 UTC, aaron-russell commented on src/app/features/bulk-upload-v2/bulk-upload-references/missing-workplace-references/missing-workplace-references-page.component.ts
> +    this.references = filter(this.activatedRoute.snapshot.data.workplaceReferences, (reference: Workplace) => {
If this is in 2 components, I would create a function in the parent directive, same with staff and just run the function.

2021-02-22 13:33 UTC, aaron-russell commented on src/app/features/bulk-upload-v2/bulk-upload-sidebar/bulk-upload-related-content/bulk-upload-related-content.component.ts
> +  }
You may as well just make authService public and use authService in view

2021-02-22 14:51 UTC, duncanc19 commented on server/models/establishment.js
> +    });
The request only seems to pass in the establishment ID but as this is used in three places I extracted it out into a function

2021-02-22 15:16 UTC, duncanc19 commented on server/models/establishment.js
> +    });
Scrap that, I've changed it to use isParent from the request, I couldn't see it when I looked

2021-02-23 08:53 UTC, aaron-russell approved these changes

2021-02-23 08:59 UTC, merged