Feat: Calculate which email template to send
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #3071
Opened 2021-03-04 16:59 UTC by chadtomkiss-madetech

**Work done**

- Added function to calculate next email template
- Filter workplaces who have already been sent an email
- Removed  `LastEmailedDate` and `EmailCount` as these are no longer needed

#### Tests
Does this PR include tests for the changes introduced?
- [x] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2021-03-04 17:02 UTC, aaron-russell requested changes

2021-03-04 17:02 UTC, aaron-russell commented on server/models/email-campaigns/inactive-workplaces/findInactiveWorkplaces.js
> +  }
Should these template ID's be in the config instead?

2021-03-04 17:05 UTC, chadtomkiss-madetech commented on server/models/email-campaigns/inactive-workplaces/findInactiveWorkplaces.js
> +  }
@aaron-russell I literally had the same idea as soon as I read through the code :joy:

2021-03-04 17:08 UTC, aaron-russell commented on server/models/email-campaigns/inactive-workplaces/findInactiveWorkplaces.js
> +  }
Great minds!

2021-03-05 11:47 UTC, aaron-russell approved these changes

2021-03-05 12:28 UTC, merged