Feat: Refactor find inactive workplaces
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #3100
Opened 2021-03-08 16:56 UTC by chadtomkiss-madetech

**Issue**

Codeclimate had some complaints about the `findInactiveWorkplaces` function.

**Work done**

- Split out `findInactiveWorkplaces` and `nextEmailTemplate` logic

#### Tests
Does this PR include tests for the changes introduced?
- [x] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2021-03-08 17:08 UTC, aaron-russell requested changes

2021-03-08 17:08 UTC, aaron-russell commented on server/models/email-campaigns/inactive-workplaces/nextEmail.js
> +}
Should this be part of the model as it's more logic, I know we never spoke about where to put logic but think it should be separate.

2021-03-08 17:18 UTC, chadtomkiss-madetech commented on server/models/email-campaigns/inactive-workplaces/nextEmail.js
> +}
@aaron-russell I think maybe the `model` could just be the refresh view / run the query

and the logic to build the inactive workplace object / determine next template could live elsewhere?

so then `models` file is just the DB logic

I'm leaning towards services :eyes:

so

```
server/models/inactive-workplaces/getInactiveWorkplaces.js

server/services/email-campaigns/inactive-workplaces/inactiveWorkplaces.js
server/services/email-campaigns/inactive-workplaces/nextEmail.js
```

2021-03-09 08:26 UTC, aaron-russell commented on server/models/email-campaigns/inactive-workplaces/nextEmail.js
> +}
Sounds good to me, yeah!

2021-03-09 14:10 UTC, merged