Feat: Keep Workplaces Active - parents db
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #3140
Opened 2021-03-16 15:03 UTC by joannafawl

#### Changes
- Added a function to get all parent workplaces and their subsidiaries
- Updated `getInactiveWorkplaces` endpoint to include parent workplaces
- Add tests

#### Tests
Does this PR include tests for the changes introduced?
- [x] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2021-03-16 15:59 UTC, aaron-russell requested changes

2021-03-16 15:59 UTC, aaron-russell commented on server/models/email-campaigns/inactive-workplaces/getParentWorkplaces.js
> +    {
Is there a reason why this is raw SQL?

2021-03-16 16:30 UTC, joannafawl commented on server/models/email-campaigns/inactive-workplaces/getParentWorkplaces.js
> +    {
It's because Sequelize doesn't support `UNION` queries

2021-03-17 08:53 UTC, aaron-russell approved these changes

2021-03-17 08:59 UTC, merged