Fix: 24 months plus inactive
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #3152
Opened 2021-03-18 16:49 UTC by chadtomkiss-madetech

**Issue**

- If a workplace had been more than 24 months inactive, they were not being included in the report.

**Work done**

- Added a `matches` function to each of the templates
- Refactored `getTemplate` to use `matches` function
- 
#### Tests
Does this PR include tests for the changes introduced?
- [x] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2021-03-18 17:34 UTC, aaron-russell requested changes

2021-03-18 17:34 UTC, aaron-russell commented on server/test/unit/services/email-campaigns/inactive-workplaces/nextEmail.spec.js
> +      console.log({ NextTemplate });
Do you need console logs of these?

2021-03-19 09:13 UTC, joannafawl approved these changes

2021-03-19 09:44 UTC, aaron-russell approved these changes

2021-03-19 09:44 UTC, merged