Fix: Accessibility Audit
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #3174
Opened 2021-03-22 14:08 UTC by joannafawl

#### Changes
- Change colour of orange banner to increase contrast
- Update `alt` text on flags so they are only used where they don't already have a description
- Change `sortBy` labels to be unique

#### Tests
Does this PR include tests for the changes introduced?
- [ ] Yes
- [ ] No, I found it difficult to test
- [x] No, they are not required for this change

2021-03-22 15:03 UTC, aaron-russell requested changes

2021-03-22 15:03 UTC, aaron-russell commented on src/app/shared/components/tabs/tabs.component.html
> +        alt="Missing or expired record alert"
This will need to be hidden visually instead, as an `<i>` tag can't have an alt

2021-03-22 15:03 UTC, aaron-russell commented on src/app/shared/components/total-staff-panel/total-staff-panel.component.html
> +      <img src="/assets/images/flag-orange.svg" alt="" />
This will need an alt as it doesn't mention what the image is showing or why it's showing

2021-03-22 16:13 UTC, joannafawl commented on src/app/shared/components/total-staff-panel/total-staff-panel.component.html
> +      <img src="/assets/images/flag-orange.svg" alt="" />
I wasn't sure with this one because the alt text for orange flags is `Expiring record alert` but this one is for missing records

2021-03-22 16:43 UTC, aaron-russell commented on src/app/shared/components/total-staff-panel/total-staff-panel.component.html
> +      <img src="/assets/images/flag-orange.svg" alt="" />
It will be `There are Missing records` or similar

2021-03-23 08:53 UTC, aaron-russell approved these changes

2021-03-23 09:11 UTC, merged