Feat/account registration survey
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #3191
Opened 2021-03-24 16:59 UTC by ross-mcfadyen

#### Tests
Does this PR include tests for the changes introduced?
- [x] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2021-03-24 17:22 UTC, ross-mcfadyen commented on package.json
> +    "db:migrration:generate": "sequelize migration:generate",
Grrrrrreat

2021-03-25 08:56 UTC, aaron-russell commented on migrations/20210323103747-addRegistrationSurveyColumnToUser.js
> +      //await queryInterface.sequelize.query('DROP TYPE cqc."enum_Establishment_OtherServicesValue";'),
Shouldn't need this comment?

2021-03-25 09:08 UTC, aaron-russell commented on server/routes/registrationSurvey.js
> +    const user = await models.user.findByUUID(req.body.userUUID);
you should be using auth here, otherwise, anyone could spoof who answered the question

2021-03-25 09:08 UTC, aaron-russell commented on server/routes/registrationSurvey.js
> +      surveyAnswers: req.body.surveyAnswers,
You're also taking what they answer verbatim, would recommend at least using celebrate to make sure you have what you expect

2021-03-25 09:27 UTC, ross-mcfadyen commented on server/models/classes/user.js
> +
Cheers. Yeah just quickly threw that in until yours was in

2021-03-25 09:31 UTC, ross-mcfadyen commented on migrations/20210324114217-accountRegistrationSurvey.js
> +          },
Could do it either way, but wasn't sure of the benefit of storing the answers in separate columns. If they're just JSON anyway it felt like the SurveyAnswers just worked as it's own thing.

2021-04-08 08:51 UTC, chadtomkiss-madetech requested changes

2021-04-08 08:51 UTC, chadtomkiss-madetech commented on server/models/email-campaigns/inactive-workplaces/getInactiveWorkplaces.js
> +  TRIM("NmdsID") AS "NmdsID",
Not sure why some changes are from the work I did last week :S

Wondering if you need to merge in `test` branch?

2021-04-08 08:51 UTC, chadtomkiss-madetech commented on server/routes/registrationSurvey.js
> +    console.error();
Think `error` needs passing to `console.error`

2021-04-08 08:51 UTC, chadtomkiss-madetech commented on src/app/core/services/user.service.ts
> +    console.log(userDetails);
Can remove console.log's

```suggestion
```

2021-04-08 08:51 UTC, chadtomkiss-madetech commented on src/app/features/registration-survey/how-did-you-hear-about/how-did-you-hear-about.component.html
> +    </a>
Could this be a submit input within the form?

2021-04-08 08:51 UTC, chadtomkiss-madetech commented on src/app/features/registration-survey/participation/participation.component.html
> +    </a>
Same here, think it could be a submit input as part of the form

2021-04-08 08:51 UTC, chadtomkiss-madetech commented on src/app/features/registration-survey/participation/participation.component.ts
> +      this.subscriptions.add(
Hmm.. typically on `ngOnDestroy` you want to remove subscriptions:

```
ngOnDestroy() {
  this.subscriptions.unsubscribe();
}
```

Not unsubscribing from Observables when a component is destroyed will keep the subscriptions open which can cause memory leaks / perf issues.

Not sure what the change is.. I think maybe subscribing to the `NavigationStart` router event in `ngOnInit`

2021-04-08 08:51 UTC, chadtomkiss-madetech commented on src/app/features/registration-survey/why-create-account/why-create-account.component.html
> +      </a>
Same here, think it can be a submit input

2021-04-08 08:51 UTC, chadtomkiss-madetech commented on src/app/core/services/registration-survey.service.ts
> +        console.log(res);
Can remove `console.log`

```suggestion
```

2021-04-08 11:31 UTC, chadtomkiss-madetech approved these changes

2021-04-08 11:32 UTC, merged