WIP: Feat/about us page
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #3503
Opened 2021-06-17 10:37 UTC by duncanc19

#### Work done
- Created pages service which retrieves pages from DirectUS
- Created a page-content component which can be reused for future pages
- Created about us page with content and article list at side
- Added tests for page-content and about-us components
- Made article and page factories for tests 

#### Tests
Does this PR include tests for the changes introduced?
- [X] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2021-06-17 14:10 UTC, aaron-russell requested changes

2021-06-17 14:10 UTC, aaron-russell commented on src/app/shared/components/page-content/page-content.component.html
> +</h1>
Should you be showing the title on the page or should it be part of the content? Also does this mean there's duplicate `h1`'s?

2021-06-17 14:15 UTC, duncanc19 commented on src/app/shared/components/page-content/page-content.component.html
> +</h1>
This component contains the title and content and the title's not in the about us component. It means we can just retrieve the data from the snapshot in this component instead of having to retrieve it every time we make a new page

2021-06-17 14:18 UTC, duncanc19 commented on src/app/shared/components/page-content/page-content.component.html
> +</h1>
Should we change the name of the component or do you think the data should be retrieved in the about us component?

2021-06-17 15:05 UTC, rramgolam commented on src/app/shared/components/page-content/page-content.component.html
> +</h1>
The `page-content` component has been renamed to `page` to cater for title + content.

2021-06-17 15:41 UTC, aaron-russell commented on src/app/shared/components/page-content/page-content.component.html
> +</h1>
Does it work for screen readers? I thought the blue heading was a `h1` that's all, and screenreaders don't like 2 `h1`'s

2021-06-17 16:02 UTC, duncanc19 commented on src/app/shared/components/page-content/page-content.component.html
> +</h1>
For pages, there isn't a caption part to the heading, articles have the caption part but they don't use this component. The article component still has the h1 with spans for the ASC-WDS news caption and the article.title

2021-06-21 08:23 UTC, aaron-russell approved these changes

2021-06-21 08:40 UTC, merged