Feat/remove nino and dob show and hide for admin
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #3542
Opened 2021-06-23 13:32 UTC by rramgolam

### Work Done
- Add permissions canViewNinoDob to permissions service and permission type to model.
- Add rendering logic for admin and non-admin cases.
- Add tests for both scenarios.

#### Tests
Does this PR include tests for the changes introduced?
- [X] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2021-06-23 13:38 UTC, aaron-russell requested changes

2021-06-23 13:38 UTC, aaron-russell commented on src/app/shared/components/staff-record-summary/personal-details/personal-details.component.html
> +        <ng-container *ngIf="!isAdmin; else showNino">
Is this not going to use the new permission you have created rather than the admin flag?

2021-06-23 14:32 UTC, rramgolam commented on src/app/shared/components/staff-record-summary/personal-details/personal-details.component.html
> +        <ng-container *ngIf="!isAdmin; else showNino">
`isAdmin` is actually coming from the new permission I created, in staff-record-summary, I fetch and set it: `this.isAdmin = this.permissionsService.can(this.workplaceUid, 'canViewNinoDob');`, then pass it along to the personal-details component. 

Shall I rename `isAdmin` to `canViewNinoDob` to make it clearer?

2021-06-23 14:36 UTC, rramgolam commented on src/app/shared/components/staff-record-summary/personal-details/personal-details.component.html
> +        <ng-container *ngIf="!isAdmin; else showNino">
(also I realised that `else showNino` doesn't need to be there, I've pushed that commit to remove it already - hence the Outdated note)

2021-06-23 14:43 UTC, aaron-russell commented on src/app/shared/components/staff-record-summary/personal-details/personal-details.component.html
> +        <ng-container *ngIf="!isAdmin; else showNino">
I think that makes more sense, otherwise `isAdmin` will be wrong later

2021-06-24 10:32 UTC, aaron-russell approved these changes

2021-06-24 10:38 UTC, merged