Tech Debt: Refactor select workplace address
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #3900
Opened 2021-08-19 15:34 UTC by joannafawl

#### Work done
- Implemented `workplaceInterfaceService`
- Moved common code into directive
- Moved common html into directive

#### Tests
Does this PR include tests for the changes introduced?
- [x] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2021-08-19 15:58 UTC, Richard-Pentecost requested changes

2021-08-19 15:58 UTC, Richard-Pentecost commented on src/app/features/add-workplace/select-workplace-address/select-workplace-address.component.ts
> +    '../../../shared/directives/create-workplace/select-workplace-address//select-workplace-address.component.html',
two forward slashes between select-workplace-address//select-workplace-address.component.html

2021-08-20 08:10 UTC, joannafawl commented on src/app/features/add-workplace/select-workplace-address/select-workplace-address.component.ts
> +    '../../../shared/directives/create-workplace/select-workplace-address//select-workplace-address.component.html',
Ooh yeah good spot!

2021-08-20 10:32 UTC, Richard-Pentecost approved these changes

2021-08-20 10:36 UTC, merged