WIP: Feat/b u toggle report fields
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #4629
Opened 2022-02-16 10:24 UTC by Richard-Pentecost

#### Work done
-

#### Tests
Does this PR include tests for the changes introduced?
- [ ] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2022-02-23 14:06 UTC, aaron-russell requested changes

2022-02-23 14:06 UTC, aaron-russell commented on src/app/features/bulk-upload/bulk-upload-page/bulk-upload-page.component.ts
> +    this.sanitise = this.isAdmin ? true : false;
Shouldn't this be the permission `canViewNinoDob`?

2022-02-23 14:06 UTC, aaron-russell commented on src/app/features/bulk-upload/drag-and-drop-files-list/drag-and-drop-files-list.component.ts
> +    //   });
Should this be removed?

2022-02-23 14:06 UTC, aaron-russell commented on src/app/features/bulk-upload/drag-and-drop-files-list/drag-and-drop-files-list.component.ts
> +        console.log(this.uploadedFiles);
Another console log

2022-02-23 14:17 UTC, Richard-Pentecost commented on src/app/features/bulk-upload/drag-and-drop-files-list/drag-and-drop-files-list.component.ts
> +        console.log(this.uploadedFiles);
Removed

2022-02-23 14:17 UTC, Richard-Pentecost commented on src/app/features/bulk-upload/drag-and-drop-files-list/drag-and-drop-files-list.component.ts
> +    //   });
removed

2022-02-23 14:18 UTC, Richard-Pentecost commented on src/app/core/services/bulk-upload.service.ts
> +    console.log(type);
Removed

2022-02-24 08:53 UTC, Richard-Pentecost commented on src/app/features/bulk-upload/bulk-upload-page/bulk-upload-page.component.ts
> +    this.sanitise = this.isAdmin ? true : false;
Done

2022-02-25 10:34 UTC, aaron-russell approved these changes

2022-02-25 11:26 UTC, merged