Set benchmarks card text dynamically
NMDSdevopsServiceAdm/SopraSteria-SFC pull request #5851
Opened 2023-06-02 15:40 UTC by Jonopono123

#### Work done
-Added additional dynamic text to benchmarks car don home page

#### Tests
Does this PR include tests for the changes introduced?
- [x] Yes
- [ ] No, I found it difficult to test
- [ ] No, they are not required for this change

2023-06-02 15:42 UTC, Zuhal-Ayob approved these changes

2023-06-02 15:56 UTC, RobertM905 requested changes

2023-06-02 15:56 UTC, RobertM905 commented on src/app/features/new-dashboard/home-tab/home-tab.component.ts
> +      } else if([1, 2, 8].filter(x => x === this.workplace.mainService.id).length > 0) {
main service id is not the thing to check against for this. (I did the same thing before). 
I merged a change into test branch that adds reportingID to the workplace.MainService object so we can use that if we can. (possible refactor in the future to add a single flag on the establishment to avoid these "Magic numbers" everywhere.)

For now use `[1, 2, 8].includes(this.workplace.mainService.reportingID)`

2023-06-02 15:56 UTC, RobertM905 commented on src/app/features/new-dashboard/home-tab/home-tab.component.ts
> +      } else if ([1, 2, 8].filter((x) => x === this.workplace.mainService.id).length > 0) {
main service id is not the thing to check against for this. (I did the same thing before).
I merged a change into test branch that adds reportingID to the workplace.MainService object so we can use that if we can. (possible refactor in the future to add a single flag on the establishment to avoid these "Magic numbers" everywhere.)

For now use [1, 2, 8].includes(this.workplace.mainService.reportingID)

2023-06-08 13:58 UTC, Jonopono123 commented on src/app/features/new-dashboard/home-tab/home-tab.component.ts
> +      } else if ([1, 2, 8].filter((x) => x === this.workplace.mainService.id).length > 0) {
Done, this now uses reportingID

2023-06-09 09:36 UTC, RobertM905 approved these changes

2023-06-09 10:57 UTC, merged